---
# This playbook only has one play
# And it applies to all hosts in the inventory file (which is dynamically
# created by Vagrant)
- hosts: all
  # we need priviledge escalation to install software, so we become root
  become: yes
  # and we become root using sudo
  become_method: sudo
  # to perform the following tasks:
  # (and tasks should always have a name)
  tasks:
    - name: Update package listing cache
      # use the Ansible apt module to:
      # update package list, but don't upgrade the system
      apt: update_cache=yes upgrade=no cache_valid_time=1800

    - name: Install packages required by GitHub Pages
      # use the Ansible apt module to:
      # install the listed packages to the latest available version
      apt: pkg={{item}} state=latest install_recommends=no
      with_items:
        - htop
        - ruby2.2
        - ruby2.2-dev
        - bundler
        - zlib1g-dev
        - ruby-execjs
      # needed by github-pages health-check:
        - libcurl3

    - name: Set Ruby 2.2.x to default
      file: src=/usr/bin/ruby2.2 dest=/usr/bin/ruby state=link

    - name: Install the GitHub Pages Ruby gem
      # use the Ansible gem module to:
      # install the listed Ruby gems to the latest available version for all users
      gem: name={{item}} state=latest user_install=no
      with_items:
        # There is a bug which forces us to explicitly install activesupport, which 
        # would otherwise be done by the github-pages gem.
        # https://github.com/github/pages-gem/issues/181
        - activesupport
        - github-pages

    - name: Copy motd
      copy: src=files/42-jekyll dest=/etc/update-motd.d/42-jekyll mode=755


